# Generated by Django 5.1.2 on 2024-12-05 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.creator'),
        ),
    ]
